import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
create function auth.role() returns text language sql as $$select 'authenticated'::text$$;
create function public.has_role(text) returns boolean language sql as $$select $1='super_admin'$$;
create function public.my_admin_id() returns uuid language sql as $$select '00000000-0000-0000-0000-000000000001'::uuid$$;
create table content_items(id uuid primary key,created_by uuid,title text,body text,caption_text text,stage text,publish_platform text,publish_platforms jsonb,published_url text,published_at timestamptz,created_at timestamptz default now(),design_file_url text);`);
const sql=fs.readFileSync(new URL('../supabase/migrations/20261008_website_publications.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
const id='00000000-0000-0000-0000-000000000002';
await db.query(`insert into content_items(id,title,stage,publish_platforms) values($1,'Post','ready_to_publish','["website"]')`,[id]);
await db.query(`select website_enqueue($1)`,[id]);await db.query(`select website_enqueue($1)`,[id]);
let job=(await db.query('select * from website_claim()')).rows[0];assert.equal(Number(job.revision),1);
assert.equal((await db.query('select * from website_claim()')).rows.length,0);
await db.query(`update content_items set title='New post' where id=$1`,[id]);
await db.query(`select website_finish($1,$2,$3,'published',201,null,'/posts/test')`,[id,job.revision,job.claim_token]);
let state=(await db.query('select * from website_publications')).rows[0];assert.equal(state.website_publish_status,'queued');assert.equal(state.payload.title,'New post');
job=(await db.query('select * from website_claim()')).rows[0];await db.query(`select website_finish($1,$2,$3,'retry',503,'HTTP_503',null)`,[id,job.revision,job.claim_token]);
assert.equal((await db.query('select * from website_claim()')).rows.length,0);
await db.exec(`update website_publications set next_attempt_at=now()`);
job=(await db.query('select * from website_claim()')).rows[0];await db.query(`select website_finish($1,$2,$3,'published',200,null,'/posts/test')`,[id,job.revision,job.claim_token]);
await db.query(`select website_enqueue($1,'unpublish')`,[id]);job=(await db.query('select * from website_claim()')).rows[0];assert.deepEqual(job.payload,{id,action:'unpublish'});
await db.query(`select website_finish($1,$2,$3,'unpublished',200,null,null)`,[id,job.revision,job.claim_token]);
await db.exec(`create or replace function public.has_role(text) returns boolean language sql as $$select false$$;`);
await assert.rejects(db.query('select website_enqueue($1)',[id]),/غير مسموح/);
assert.equal(Number((await db.query('select count(*) n from website_publish_attempts')).rows[0].n),4);
await db.close();console.log('PASS migration repeatability, authorization, deduplication, exclusive claim, concurrent edit, retry delay, update and unpublish queue');
