const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path'),ts=require('typescript'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{
 const dom=new JSDOM('<select id="cf-brand"><option value="dr_dina">Dina</option><option value="sono">Sono</option></select><select id="cf-content-kind"><option value="standard">standard</option><option value="doctor_intro">doctor</option></select>',{runScripts:'outside-only'}),w=dom.window;
 w.eval(read('assets/js/dina-content.js'));const api=w.SSMPDDinaContent;w.document.body.insertAdjacentHTML('beforeend',api.html());api.wire(w.document.body);
 assert.equal(w.document.querySelector('#dina-content-fields').hidden,false);
 const mapping={};for(const [kind,profile] of Object.entries(api.kinds)){for(const variant of profile.variants){mapping[variant]=kind;api.hydrate({kind,variant,audience:'older_adults',source_text:'مصدر طبي مرفق للمراجعة يحتوي معلومات للموظف قبل الاعتماد والنشر',source_url:'https://example.org/paper'});const b=api.current(true);assert.equal(b.variant,variant);assert.equal(b.kind,kind);assert(w.document.querySelector('#dina-template-preview').src.includes('/'+variant+'.webp'));const saved=api.metadata({design_body:'نص داخلي'},b);assert.equal(api.from({brand:'dr_dina',agent_raw_output:JSON.stringify(saved)}).copy.design_body,'نص داخلي');}}
 assert.equal(Object.keys(mapping).length,12);
 api.hydrate({kind:'research',variant:4});assert.throws(()=>api.current(true),/المصدر/);
 w.document.querySelector('#cf-brand').value='sono';w.document.querySelector('#cf-brand').dispatchEvent(new w.Event('change'));assert.equal(api.current(true),null);assert(w.document.querySelector('#dina-content-fields').hidden);
 w.document.querySelector('#cf-brand').value='dr_dina';w.document.querySelector('#cf-content-kind').value='doctor_intro';w.document.querySelector('#cf-content-kind').dispatchEvent(new w.Event('change'));assert.equal(api.current(true),null);
 w.document.querySelector('#cf-content-kind').value='standard';w.document.body.insertAdjacentHTML('beforeend','<input id="cf-title" value="باركنسون"><textarea id="cf-agent-raw"></textarea><textarea id="cf-body"></textarea>');api.hydrate({kind:'qa',variant:5,audience:'older_adults'});
 w.SSMPDDoctorContent={current:()=>null};w.SSMPDWorkflow={objectiveSelectHtml:id=>'<select id="'+id+'"><option value="awareness">awareness</option></select>',getContentAIBrief:async()=>''};let sent;
 w.SSMPDDb={generateContentIdeas:async body=>{sent=body;return {ideas:Array.from({length:3},()=>({title:'عنوان',idea:'فكرة',format:'image_post',dina_brief:body.dina_brief,design_body:'نص داخل التصميم',design_headline:'الرعشة مش العلامة الوحيدة',design_subtitle:'لاحظ التغيرات بدري',design_cta:'احفظ البوست'}))};}};w.eval(read('assets/js/content-ai.js'));w.SSMPDContentAI.openGenerator();w.document.querySelector('#ai-generate').click();await new Promise(r=>setTimeout(r,20));assert.equal(sent.dina_brief.variant,5);assert.equal(sent.preferred_format,'image_post');w.document.querySelector('[data-use]').click();const selected=JSON.parse(w.document.querySelector('#cf-agent-raw').value);assert.equal(selected.design_body,'نص داخل التصميم');assert.equal(selected.dina_brief.audience,'older_adults');
 let handler,calls=0,last,oversized=false,item={brand:'dr_dina',agent_raw_output:'{}'};
 const db={rpc:async()=>({data:'staff'}),from:()=>({select:()=>({eq:()=>({single:async()=>({data:item})})})})};
 const context=vm.createContext({console,Request,Response,createClient:()=>db,Deno:{env:{get:k=>k==='CONTENT_AI_MODEL'?'gpt-4.1-mini':'test'},serve:f=>handler=f},fetch:async(url,options)=>{calls++;last=JSON.parse(options.body);const input=JSON.parse(last.input.replace(/^SSMPD Dashboard Brief:\n/,'')),b=input.dina_brief;const copy={design_headline:'حركة أهدى كل يوم',design_subtitle:'فهم العلامات يساعدك تاخد الخطوة المناسبة',design_cta:'احفظ البوست'};if(b)Object.assign(copy,{design_secondary_headline:'',design_body:b.variant<=5?(oversized?Array(40).fill('نص').join(' '):'ملخص المصدر الطبي المتاح'):'',design_scene_brief:'An older Egyptian adult in a calm natural medical education scene'});const idea={...copy,title:'عنوان',idea:'فكرة',hook:'افتتاحية',angle:'زاوية',format:input.preferred_format||'image_post',script:null,caption:'نص للمراجعة',cta_type:'save_share',cta_text:'احفظ البوست',duration_min_seconds:null,duration_max_seconds:null,video_template:null,hypothesis_reason:'تجربة'};return Response.json({output_text:JSON.stringify(last.text.format.schema.properties.ideas?{ideas:[idea,idea,idea]}:copy)});}});
 const source=read('supabase/functions/content-ai/index.ts').replace(/^import .*\n/,'');const transpiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None},reportDiagnostics:true});assert(!transpiled.diagnostics?.length);vm.runInContext(transpiled.outputText,context);
 const run=body=>handler(new Request('https://example.org',{method:'POST',headers:{Authorization:'Bearer staff','Content-Type':'application/json'},body:JSON.stringify(body)}));
 for(let variant=1;variant<=12;variant++){const b={kind:mapping[variant],variant,audience:'older_adults',source_text:'نص مرجع طبي متاح تمت إضافته للمراجعة دون ادعاء تصفح الويب',source_url:'https://example.org/paper'};const res=await run({brand:'dr_dina',dina_brief:b,preferred_format:'video'});assert.equal(res.status,200);const out=await res.json();assert.equal(out.ideas.length,3);assert.equal(out.ideas[0].format,'image_post');assert.equal(out.ideas[0].dina_brief.variant,variant);assert.equal('design_body' in last.text.format.schema.properties.ideas.items.properties,true);assert(last.instructions.includes('القالب '+variant));}
 const before=calls;assert.equal((await run({brand:'dr_dina',dina_brief:{kind:'qa',variant:4}})).status,400);assert.equal((await run({brand:'dr_dina',dina_brief:{kind:'research',variant:4}})).status,400);assert.equal((await run({brand:'sono',dina_brief:{kind:'qa',variant:5}})).status,400);assert.equal(calls,before,'Invalid briefs never call a paid provider');
 oversized=true;assert.equal((await run({brand:'dr_dina',dina_brief:{kind:'qa',variant:5}})).status,400);oversized=false;
 assert.equal((await run({brand:'sono',preferred_format:'image_post'})).status,200);assert.equal('design_body' in last.text.format.schema.properties.ideas.items.properties,false,'Sono schema remains unchanged');
 item.agent_raw_output=JSON.stringify({dina_brief:{kind:'qa',variant:5,audience:'adults'}});const res=await run({mode:'design_copy',content_id:'existing'});assert.equal(res.status,200);assert.equal((await res.json()).design_copy.design_body,'ملخص المصدر الطبي المتاح');assert(last.instructions.includes('سؤال وجواب'));
 console.log('PASS: all 12 profiles, audience/source validation, UI selection and metadata restore, full Edge handler/schema, invalid requests before provider, word limits, existing copy proposals and Sono compatibility. No paid requests.');
 dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
