import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!,SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,ANON=Deno.env.get("SUPABASE_ANON_KEY")!;
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8","Cache-Control":"private, no-store"}});
const day=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
function stamp(d:string,t:string){const[a,b,c]=d.split("-").map(Number),[h,m]=t.slice(0,5).split(":").map(Number);return Date.UTC(a,b-1,c,h,m)}
function part(ms:number){const d=new Date(ms),date=d.getUTCFullYear()+"-"+String(d.getUTCMonth()+1).padStart(2,"0")+"-"+String(d.getUTCDate()).padStart(2,"0"),time=String(d.getUTCHours()).padStart(2,"0")+":"+String(d.getUTCMinutes()).padStart(2,"0");return{scheduled_key:date+"T"+time,scheduled_date:date,scheduled_time:time}}
function doses(m:any,d:string){const start=stamp(m.start_date,m.start_time||"08:00"),step=Number(m.frequency_hours)*3600000,end=start+Number(m.duration_days)*86400000,first=Math.max(0,Math.ceil((stamp(d,"00:00")-start)/step)),last=stamp(d,"23:59"),out=[];for(let i=first;;i++){const n=start+i*step;if(n>last||n>=end)break;out.push(part(n))}return out}
async function ctx(req:Request,a:any){const h=req.headers.get("Authorization")||"";if(!h.toLowerCase().startsWith("bearer "))return null;const u=await createClient(URL,ANON,{global:{headers:{Authorization:h}}}).auth.getUser();if(!u.data.user)return null;const q=await a.from("patient_accounts").select("id,status,activation_completed_at").eq("auth_user_id",u.data.user.id).maybeSingle(),account=q.data;if(!account||account.status!=="active"||!account.activation_completed_at)return null;const x=await a.from("patient_account_access").select("patient_id,expires_at,revoked_at,verification_status").eq("account_id",account.id).eq("verification_status","approved");return{account,ids:Array.from(new Set((x.data||[]).filter((r:any)=>!r.revoked_at&&(!r.expires_at||new Date(r.expires_at)>new Date())).map((r:any)=>r.patient_id)))}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{headers:CORS});if(req.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405);let b:any;try{b=await req.json()}catch{return json({error:"INVALID_JSON"},400)}const a=createClient(URL,SERVICE),c=await ctx(req,a);if(!c)return json({error:"PATIENT_ACCOUNT_NOT_ACTIVATED"},403);try{const v=await a.from("patient_visits").select("id,patient_id,doctor_name,specialty").in("patient_id",c.ids),by=new Map((v.data||[]).map((x:any)=>[x.id,x])),ids=Array.from(by.keys()),today=day();if(!ids.length)return json({day:today,medications:[]});if(b.op==="overview"){const q=await a.from("patient_visit_medications").select("*").in("visit_id",ids).eq("status","active"),meds=(q.data||[]).filter((m:any)=>doses(m,today).length),mi=meds.map((m:any)=>m.id),z=mi.length?await a.from("patient_medication_dose_completions").select("medication_id,scheduled_key,status,taken_at").in("medication_id",mi).eq("scheduled_date",today):{data:[]},state=new Map((z.data||[]).map((x:any)=>[x.medication_id+"|"+x.scheduled_key,x]));return json({day:today,medications:meds.map((m:any)=>({...m,visit:by.get(m.visit_id),doses:doses(m,today).map((d:any)=>({...d,completion:state.get(m.id+"|"+d.scheduled_key)||null}))}))})}if(b.op!=="set_dose"||typeof b.medication_id!=="string"||!["taken","missed"].includes(b.status))return json({error:"INVALID_DOSE"},400);const q=await a.from("patient_visit_medications").select("*").eq("id",b.medication_id).maybeSingle(),m=q.data;if(!m||!by.has(m.visit_id)||m.status!=="active")return json({error:"NO_APPROVED_MEDICAL_ACCESS"},403);const d=doses(m,today).find((x:any)=>x.scheduled_key===b.scheduled_key);if(!d)return json({error:"DOSE_NOT_AVAILABLE"},400);const now=new Date().toISOString(),w=await a.from("patient_medication_dose_completions").upsert({...d,medication_id:m.id,status:b.status,taken_at:b.status==="taken"?now:null,recorded_by_account_id:c.account.id,updated_at:now},{onConflict:"medication_id,scheduled_key"}).select("medication_id,scheduled_key,status,taken_at,updated_at").single();if(w.error)throw w.error;return json({ok:true,completion:w.data,day:today})}catch(e){console.error(e);return json({error:"MEDICATION_REQUEST_FAILED"},500)}});